### ISSUE TITLE
--num-workers nonzero causes a hang in fairseq's transformer after a few epochs

### ISSUE THREAD

**Issue by taylanbil** [pytorch-tpu/examples#14]
When GroupedIterator is removed from code, i.e. line `itr = iterators.GroupedIterator(itr, update_freq)` is commented out, hang does not happen. Something about the combination of GroupedIterator, multi-processes and threads does not work well.

We get a bunch of ignored exceptions:
```
Exception ignored in: <bound method _MultiProcessingDataLoaderIter.__del__ of <torch.utils.data.dataloader._MultiProcessingDataLoaderIter object at 0x7fffe0a234e0>>
Traceback (most recent call last):
  File "/anaconda3/envs/pytorch-nightly/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 926, in __del__
    self._shutdown_workers()
  File "/anaconda3/envs/pytorch-nightly/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 906, in _shutdown_workers
    w.join()
  File "/anaconda3/envs/pytorch-nightly/lib/python3.6/multiprocessing/process.py", line 122, in join
    assert self._parent_pid == os.getpid(), 'can only join a child process'
AssertionError: can only join a child process
```
and it eventually hangs.

**Comment by taylanbil** [comment]
We switched to multi-processing and threads went away, this issue is obsolete.
